/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author alvesrc
 */
public class JanelaMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMainMenu
     */
    public JanelaMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGanhos = new javax.swing.JButton();
        buttonDespesas = new javax.swing.JButton();
        buttonRelatorios = new javax.swing.JButton();
        buttonGraficos = new javax.swing.JButton();
        buttonSimulador = new javax.swing.JButton();
        buttonOpcoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[SGF - 2014] Main Menu");
        setResizable(false);

        buttonGanhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/32px_ganhos.png"))); // NOI18N
        buttonGanhos.setText("Ganhos");
        buttonGanhos.setToolTipText("Cadastrar, remover ou buscar ganhos.");
        buttonGanhos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonGanhos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonGanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGanhosActionPerformed(evt);
            }
        });

        buttonDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/32px_despesas.png"))); // NOI18N
        buttonDespesas.setText("Despesas");
        buttonDespesas.setToolTipText("Cadastrar, remover ou buscar despesas.");
        buttonDespesas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDespesas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDespesasActionPerformed(evt);
            }
        });

        buttonRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/32px_relatorio.png"))); // NOI18N
        buttonRelatorios.setText("Relatorios");
        buttonRelatorios.setToolTipText("Exibir balanços.");
        buttonRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGraficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/32px_grafico.png"))); // NOI18N
        buttonGraficos.setText("Gráficos");
        buttonGraficos.setToolTipText("Plotar os ganhos, despesas e balanço.");
        buttonGraficos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonGraficos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonSimulador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/32px_simulador.png"))); // NOI18N
        buttonSimulador.setText("Simulador");
        buttonSimulador.setToolTipText("Simular compras a vista ou parceladas.");
        buttonSimulador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSimulador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/32px_opcoes.png"))); // NOI18N
        buttonOpcoes.setText("Opções");
        buttonOpcoes.setToolTipText("Alterar opções do software.");
        buttonOpcoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOpcoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGanhosActionPerformed
        // TODO add your handling code here:
        JanelaGanhos janelaGanhos = new JanelaGanhos();
        this.dispose();
        janelaGanhos.setVisible(true);
    }//GEN-LAST:event_buttonGanhosActionPerformed

    private void buttonDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDespesasActionPerformed
        // TODO add your handling code here:
        JanelaDespesas janelaDespesas = new JanelaDespesas();
        this.dispose();
        janelaDespesas.setVisible(true);
    }//GEN-LAST:event_buttonDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaMainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDespesas;
    private javax.swing.JButton buttonGanhos;
    private javax.swing.JButton buttonGraficos;
    private javax.swing.JButton buttonOpcoes;
    private javax.swing.JButton buttonRelatorios;
    private javax.swing.JButton buttonSimulador;
    // End of variables declaration//GEN-END:variables
}
