/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author AlvesRC
 */
public class JanelaDespesas extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastroGasto
     */
    public JanelaDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        panelCadastrarDespesa = new javax.swing.JPanel();
        labelCadastrarDespesalAviso = new javax.swing.JLabel();
        panelCadastrarDespesaDados = new javax.swing.JPanel();
        labelCadastrarDespesaDesc = new javax.swing.JLabel();
        labelCadastrarDespesaValor = new javax.swing.JLabel();
        fieldInputCadastrarDespesaDesc = new javax.swing.JTextField();
        fieldInputCadastrarDespesaValor = new javax.swing.JFormattedTextField();
        panelCadastrarDespesaData = new javax.swing.JPanel();
        labelCadastrarDespesaDia = new javax.swing.JLabel();
        labelCadastrarDespesaMes = new javax.swing.JLabel();
        labelCadastrarDespesaAno = new javax.swing.JLabel();
        spinnerCadastrarDespesaDia = new javax.swing.JSpinner();
        spinnerCadastrarDespesaMes = new javax.swing.JSpinner();
        spinnerCadastrarDespesaAno = new javax.swing.JSpinner();
        buttonCadastrarDespesaLimpar = new javax.swing.JButton();
        buttonCadastrarDespesaAdicionar = new javax.swing.JButton();
        buttonCadastrarDespesaCancelar = new javax.swing.JButton();
        panellRemoverDespesa = new javax.swing.JPanel();
        labelRemoverDespesalAviso = new javax.swing.JLabel();
        panelRemoverDespesaDados = new javax.swing.JPanel();
        labelRemoverDespesaDesc = new javax.swing.JLabel();
        fieldInputRemoverDespesaDesc = new javax.swing.JTextField();
        panelRemoverDespesaData = new javax.swing.JPanel();
        labelRemoverDespesaDia = new javax.swing.JLabel();
        labelRemoverDespesaMes = new javax.swing.JLabel();
        labelRemoverDespesaAno = new javax.swing.JLabel();
        spinnerRemoverDespesaDia = new javax.swing.JSpinner();
        spinnerRemoverDespesaMes = new javax.swing.JSpinner();
        spinnerRemoverDespesaAno = new javax.swing.JSpinner();
        buttonRemoverDespesaLimpar = new javax.swing.JButton();
        buttonRemoverDespesaRemover = new javax.swing.JButton();
        buttonRemoverDespesaCancelar = new javax.swing.JButton();
        panelBuscarDespesa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[SGF - 2014] Despesas");
        setLocationByPlatform(true);
        setResizable(false);

        labelCadastrarDespesalAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCadastrarDespesalAviso.setText("Insira os dados da despesa a ser cadastrada:");
        labelCadastrarDespesalAviso.setToolTipText("");

        panelCadastrarDespesaDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelCadastrarDespesaDesc.setText("Descrição:");

        labelCadastrarDespesaValor.setText("Valor:");

        fieldInputCadastrarDespesaDesc.setToolTipText("Uma breve descrição da despesa a ser cadastrada.");

        fieldInputCadastrarDespesaValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        fieldInputCadastrarDespesaValor.setText("R$ 1.000,00");
        fieldInputCadastrarDespesaValor.setToolTipText("O valor da despesa.");

        javax.swing.GroupLayout panelCadastrarDespesaDadosLayout = new javax.swing.GroupLayout(panelCadastrarDespesaDados);
        panelCadastrarDespesaDados.setLayout(panelCadastrarDespesaDadosLayout);
        panelCadastrarDespesaDadosLayout.setHorizontalGroup(
            panelCadastrarDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarDespesaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarDespesaValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastrarDespesaDesc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldInputCadastrarDespesaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldInputCadastrarDespesaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadastrarDespesaDadosLayout.setVerticalGroup(
            panelCadastrarDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarDespesaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarDespesaDesc)
                    .addComponent(fieldInputCadastrarDespesaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarDespesaValor)
                    .addComponent(fieldInputCadastrarDespesaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCadastrarDespesaData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelCadastrarDespesaDia.setText("Dia:");

        labelCadastrarDespesaMes.setText("Mês:");

        labelCadastrarDespesaAno.setText("Ano:");

        spinnerCadastrarDespesaDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerCadastrarDespesaDia.setToolTipText("O dia em que a despesa ocorreu.");

        spinnerCadastrarDespesaMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerCadastrarDespesaMes.setToolTipText("O mês em que a despesa ocorreu.");

        spinnerCadastrarDespesaAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerCadastrarDespesaAno.setToolTipText("O ano em que a despesa ocorreu.");

        javax.swing.GroupLayout panelCadastrarDespesaDataLayout = new javax.swing.GroupLayout(panelCadastrarDespesaData);
        panelCadastrarDespesaData.setLayout(panelCadastrarDespesaDataLayout);
        panelCadastrarDespesaDataLayout.setHorizontalGroup(
            panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarDespesaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarDespesaDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastrarDespesaMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastrarDespesaAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerCadastrarDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCadastrarDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerCadastrarDespesaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelCadastrarDespesaDataLayout.setVerticalGroup(
            panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarDespesaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarDespesaDia)
                    .addComponent(spinnerCadastrarDespesaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarDespesaMes)
                    .addComponent(spinnerCadastrarDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarDespesaAno)
                    .addComponent(spinnerCadastrarDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonCadastrarDespesaLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonCadastrarDespesaLimpar.setText("Limpar");
        buttonCadastrarDespesaLimpar.setToolTipText("Limpar os campos da tela.");

        buttonCadastrarDespesaAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_adicionar.png"))); // NOI18N
        buttonCadastrarDespesaAdicionar.setText("Adicionar");
        buttonCadastrarDespesaAdicionar.setToolTipText("Cadastrar a despesa no banco de dados.");

        buttonCadastrarDespesaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonCadastrarDespesaCancelar.setText("Cancelar");
        buttonCadastrarDespesaCancelar.setToolTipText("Cancelar o cadastro.");

        javax.swing.GroupLayout panelCadastrarDespesaLayout = new javax.swing.GroupLayout(panelCadastrarDespesa);
        panelCadastrarDespesa.setLayout(panelCadastrarDespesaLayout);
        panelCadastrarDespesaLayout.setHorizontalGroup(
            panelCadastrarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelCadastrarDespesaLayout.createSequentialGroup()
                        .addComponent(buttonCadastrarDespesaCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastrarDespesaAdicionar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadastrarDespesaLayout.createSequentialGroup()
                        .addComponent(labelCadastrarDespesalAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastrarDespesaLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadastrarDespesaLayout.createSequentialGroup()
                        .addComponent(panelCadastrarDespesaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCadastrarDespesaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadastrarDespesaLayout.setVerticalGroup(
            panelCadastrarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarDespesalAviso)
                    .addComponent(buttonCadastrarDespesaLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadastrarDespesaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCadastrarDespesaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrarDespesaAdicionar)
                    .addComponent(buttonCadastrarDespesaCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Cadastrar", panelCadastrarDespesa);

        labelRemoverDespesalAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelRemoverDespesalAviso.setText("Insira os dados da despesa a ser cadastrada:");
        labelRemoverDespesalAviso.setToolTipText("");

        panelRemoverDespesaDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelRemoverDespesaDesc.setText("Descrição:");

        fieldInputRemoverDespesaDesc.setToolTipText("Uma breve descrição da despesa a ser cadastrada.");

        javax.swing.GroupLayout panelRemoverDespesaDadosLayout = new javax.swing.GroupLayout(panelRemoverDespesaDados);
        panelRemoverDespesaDados.setLayout(panelRemoverDespesaDadosLayout);
        panelRemoverDespesaDadosLayout.setHorizontalGroup(
            panelRemoverDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverDespesaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRemoverDespesaDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldInputRemoverDespesaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRemoverDespesaDadosLayout.setVerticalGroup(
            panelRemoverDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverDespesaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverDespesaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverDespesaDesc)
                    .addComponent(fieldInputRemoverDespesaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRemoverDespesaData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelRemoverDespesaDia.setText("Dia:");

        labelRemoverDespesaMes.setText("Mês:");

        labelRemoverDespesaAno.setText("Ano:");

        spinnerRemoverDespesaDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerRemoverDespesaDia.setToolTipText("O dia em que a despesa ocorreu.");

        spinnerRemoverDespesaMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerRemoverDespesaMes.setToolTipText("O mês em que a despesa ocorreu.");

        spinnerRemoverDespesaAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerRemoverDespesaAno.setToolTipText("O ano em que a despesa ocorreu.");

        javax.swing.GroupLayout panelRemoverDespesaDataLayout = new javax.swing.GroupLayout(panelRemoverDespesaData);
        panelRemoverDespesaData.setLayout(panelRemoverDespesaDataLayout);
        panelRemoverDespesaDataLayout.setHorizontalGroup(
            panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverDespesaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRemoverDespesaDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemoverDespesaMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemoverDespesaAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerRemoverDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRemoverDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRemoverDespesaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelRemoverDespesaDataLayout.setVerticalGroup(
            panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverDespesaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverDespesaDia)
                    .addComponent(spinnerRemoverDespesaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverDespesaMes)
                    .addComponent(spinnerRemoverDespesaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRemoverDespesaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverDespesaAno)
                    .addComponent(spinnerRemoverDespesaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonRemoverDespesaLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonRemoverDespesaLimpar.setText("Limpar");

        buttonRemoverDespesaRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_delete.png"))); // NOI18N
        buttonRemoverDespesaRemover.setText("Remover");

        buttonRemoverDespesaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonRemoverDespesaCancelar.setText("Cancelar");

        javax.swing.GroupLayout panellRemoverDespesaLayout = new javax.swing.GroupLayout(panellRemoverDespesa);
        panellRemoverDespesa.setLayout(panellRemoverDespesaLayout);
        panellRemoverDespesaLayout.setHorizontalGroup(
            panellRemoverDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellRemoverDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellRemoverDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panellRemoverDespesaLayout.createSequentialGroup()
                        .addComponent(buttonRemoverDespesaCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRemoverDespesaRemover))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panellRemoverDespesaLayout.createSequentialGroup()
                        .addComponent(labelRemoverDespesalAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRemoverDespesaLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panellRemoverDespesaLayout.createSequentialGroup()
                        .addComponent(panelRemoverDespesaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRemoverDespesaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellRemoverDespesaLayout.setVerticalGroup(
            panellRemoverDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellRemoverDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panellRemoverDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverDespesalAviso)
                    .addComponent(buttonRemoverDespesaLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panellRemoverDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRemoverDespesaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRemoverDespesaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panellRemoverDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRemoverDespesaCancelar)
                    .addComponent(buttonRemoverDespesaRemover))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Remover", panellRemoverDespesa);

        panelBuscarDespesa.setPreferredSize(new java.awt.Dimension(473, 231));

        javax.swing.GroupLayout panelBuscarDespesaLayout = new javax.swing.GroupLayout(panelBuscarDespesa);
        panelBuscarDespesa.setLayout(panelBuscarDespesaLayout);
        panelBuscarDespesaLayout.setHorizontalGroup(
            panelBuscarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        panelBuscarDespesaLayout.setVerticalGroup(
            panelBuscarDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Buscar", panelBuscarDespesa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainTabbedPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(mainTabbedPane)
                    .addGap(1, 1, 1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarDespesaAdicionar;
    private javax.swing.JButton buttonCadastrarDespesaCancelar;
    private javax.swing.JButton buttonCadastrarDespesaLimpar;
    private javax.swing.JButton buttonRemoverDespesaCancelar;
    private javax.swing.JButton buttonRemoverDespesaLimpar;
    private javax.swing.JButton buttonRemoverDespesaRemover;
    private javax.swing.JTextField fieldInputCadastrarDespesaDesc;
    private javax.swing.JFormattedTextField fieldInputCadastrarDespesaValor;
    private javax.swing.JTextField fieldInputRemoverDespesaDesc;
    private javax.swing.JLabel labelCadastrarDespesaAno;
    private javax.swing.JLabel labelCadastrarDespesaDesc;
    private javax.swing.JLabel labelCadastrarDespesaDia;
    private javax.swing.JLabel labelCadastrarDespesaMes;
    private javax.swing.JLabel labelCadastrarDespesaValor;
    private javax.swing.JLabel labelCadastrarDespesalAviso;
    private javax.swing.JLabel labelRemoverDespesaAno;
    private javax.swing.JLabel labelRemoverDespesaDesc;
    private javax.swing.JLabel labelRemoverDespesaDia;
    private javax.swing.JLabel labelRemoverDespesaMes;
    private javax.swing.JLabel labelRemoverDespesalAviso;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel panelBuscarDespesa;
    private javax.swing.JPanel panelCadastrarDespesa;
    private javax.swing.JPanel panelCadastrarDespesaDados;
    private javax.swing.JPanel panelCadastrarDespesaData;
    private javax.swing.JPanel panelRemoverDespesaDados;
    private javax.swing.JPanel panelRemoverDespesaData;
    private javax.swing.JPanel panellRemoverDespesa;
    private javax.swing.JSpinner spinnerCadastrarDespesaAno;
    private javax.swing.JSpinner spinnerCadastrarDespesaDia;
    private javax.swing.JSpinner spinnerCadastrarDespesaMes;
    private javax.swing.JSpinner spinnerRemoverDespesaAno;
    private javax.swing.JSpinner spinnerRemoverDespesaDia;
    private javax.swing.JSpinner spinnerRemoverDespesaMes;
    // End of variables declaration//GEN-END:variables
}
