/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.Controle;
import dados.Ganho;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago Matos
 */
public class JanelaGanhos extends javax.swing.JFrame {

    //Controle do programa
    private Controle core;
    
    /**
     * Método para definir um controle do programa para esta janela
     * @param newCore O core a ser utilizado pela janela
     */
    public void setCore(Controle newCore){
        core = newCore;
    }
    
    /**
     * Creates new form JanelaGanhos
     */
    public JanelaGanhos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        panelCadastrarGanho = new javax.swing.JPanel();
        labelCadastrarGanhoAviso = new javax.swing.JLabel();
        panelCadastroGanhoData = new javax.swing.JPanel();
        labelCadastroGanhoDataDia = new javax.swing.JLabel();
        spinnerCadastroGanhoDataDia = new javax.swing.JSpinner();
        labelCadastroGanhoDataMes = new javax.swing.JLabel();
        labelCadastroGanhoDataAno = new javax.swing.JLabel();
        spinnerCadastroGanhoDataMes = new javax.swing.JSpinner();
        spinnerCadastroGanhoDataAno = new javax.swing.JSpinner();
        panelCadastroGanhoDados = new javax.swing.JPanel();
        labelCadastrarGanhoDesc = new javax.swing.JLabel();
        labelCadastrarGanhoValor = new javax.swing.JLabel();
        fieldInputCadastrarGanhoDesc = new javax.swing.JTextField();
        fieldInputCadastrarGanhoValor = new javax.swing.JTextField();
        buttonCadastroGanhoLimpar = new javax.swing.JButton();
        buttonCadastroGanhoCancelar = new javax.swing.JButton();
        buttonCadastroGanhoAdicionar = new javax.swing.JButton();
        paneRemoverGanho = new javax.swing.JPanel();
        labelRemoverGanhoAviso = new javax.swing.JLabel();
        panelRemoverGanhoDados = new javax.swing.JPanel();
        labelRemoverGanhoDesc = new javax.swing.JLabel();
        fieldInputRemoverGanhoDesc = new javax.swing.JTextField();
        panelRemoverGanhoData = new javax.swing.JPanel();
        labelRemoverGanhoDia = new javax.swing.JLabel();
        labelRemoverGanhoMes = new javax.swing.JLabel();
        labelRemoverGanhoAno = new javax.swing.JLabel();
        spinnerRemoverGanhoDia = new javax.swing.JSpinner();
        spinnerRemoverGanhoMes = new javax.swing.JSpinner();
        spinnerRemoverGanhoAno = new javax.swing.JSpinner();
        buttonRemoverGanhoLimpar = new javax.swing.JButton();
        buttonRemoverGanhoRemover = new javax.swing.JButton();
        buttonRemoverGanhoCancelar = new javax.swing.JButton();
        panelBuscarGanho = new javax.swing.JPanel();
        labelCadastrarGanhoAviso1 = new javax.swing.JLabel();
        panelCadastroGanhoData1 = new javax.swing.JPanel();
        labelBuscarGanhoDataDia = new javax.swing.JLabel();
        spinnerBuscarGanhoDataDia = new javax.swing.JSpinner();
        labelBuscarGanhoDataMes = new javax.swing.JLabel();
        labelBuscarGanhoDataAno = new javax.swing.JLabel();
        spinnerBuscarGanhoDataMes = new javax.swing.JSpinner();
        spinnerBuscarGanhoDataAno = new javax.swing.JSpinner();
        panelCadastroGanhoDados1 = new javax.swing.JPanel();
        labelBuscarGanhoDesc = new javax.swing.JLabel();
        labelBuscarGanhoValor = new javax.swing.JLabel();
        fieldInputBuscarGanhoDesc = new javax.swing.JTextField();
        fieldOutputBuscarGanhoValor = new javax.swing.JTextField();
        buttonBuscarGanhoLimpar = new javax.swing.JButton();
        buttonBuscarGanhoCancelar = new javax.swing.JButton();
        buttonBuscarGanhoBuscar = new javax.swing.JButton();
        panelListarGanho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[SGF - 2014] Ganhos");
        setLocationByPlatform(true);
        setResizable(false);

        labelCadastrarGanhoAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCadastrarGanhoAviso.setText("Insira os dados do ganho a ser cadastrado:");

        panelCadastroGanhoData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelCadastroGanhoDataDia.setText("Dia:");

        spinnerCadastroGanhoDataDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerCadastroGanhoDataDia.setToolTipText("O dia em que o ganho ocorreu.");

        labelCadastroGanhoDataMes.setText("Mês:");

        labelCadastroGanhoDataAno.setText("Ano:");

        spinnerCadastroGanhoDataMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerCadastroGanhoDataMes.setToolTipText("O mês em que o ganho ocorreu.");

        spinnerCadastroGanhoDataAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerCadastroGanhoDataAno.setToolTipText("O ano em que o ganho ocorreu.");

        javax.swing.GroupLayout panelCadastroGanhoDataLayout = new javax.swing.GroupLayout(panelCadastroGanhoData);
        panelCadastroGanhoData.setLayout(panelCadastroGanhoDataLayout);
        panelCadastroGanhoDataLayout.setHorizontalGroup(
            panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastroGanhoDataDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastroGanhoDataMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastroGanhoDataAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerCadastroGanhoDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerCadastroGanhoDataDia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerCadastroGanhoDataMes, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        panelCadastroGanhoDataLayout.setVerticalGroup(
            panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroGanhoDataDia)
                    .addComponent(spinnerCadastroGanhoDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroGanhoDataMes)
                    .addComponent(spinnerCadastroGanhoDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroGanhoDataAno)
                    .addComponent(spinnerCadastroGanhoDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCadastroGanhoDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelCadastrarGanhoDesc.setText("Descrição:");

        labelCadastrarGanhoValor.setText("Valor:");

        fieldInputCadastrarGanhoDesc.setToolTipText("Uma breve descrição do ganho a ser cadastrado.");

        javax.swing.GroupLayout panelCadastroGanhoDadosLayout = new javax.swing.GroupLayout(panelCadastroGanhoDados);
        panelCadastroGanhoDados.setLayout(panelCadastroGanhoDadosLayout);
        panelCadastroGanhoDadosLayout.setHorizontalGroup(
            panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarGanhoValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastrarGanhoDesc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldInputCadastrarGanhoDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(fieldInputCadastrarGanhoValor))
                .addContainerGap())
        );
        panelCadastroGanhoDadosLayout.setVerticalGroup(
            panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarGanhoDesc)
                    .addComponent(fieldInputCadastrarGanhoDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarGanhoValor)
                    .addComponent(fieldInputCadastrarGanhoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonCadastroGanhoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonCadastroGanhoLimpar.setText("Limpar");
        buttonCadastroGanhoLimpar.setToolTipText("Limpar os campos da tela.");
        buttonCadastroGanhoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroGanhoLimparActionPerformed(evt);
            }
        });

        buttonCadastroGanhoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonCadastroGanhoCancelar.setText("Cancelar");
        buttonCadastroGanhoCancelar.setToolTipText("Cancelar o cadastro.");
        buttonCadastroGanhoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroGanhoCancelarActionPerformed(evt);
            }
        });

        buttonCadastroGanhoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_adicionar.png"))); // NOI18N
        buttonCadastroGanhoAdicionar.setText("Adicionar");
        buttonCadastroGanhoAdicionar.setToolTipText("Cadastrar o ganho no banco de dados.");
        buttonCadastroGanhoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroGanhoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastrarGanhoLayout = new javax.swing.GroupLayout(panelCadastrarGanho);
        panelCadastrarGanho.setLayout(panelCadastrarGanhoLayout);
        panelCadastrarGanhoLayout.setHorizontalGroup(
            panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarGanhoLayout.createSequentialGroup()
                        .addComponent(panelCadastroGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCadastroGanhoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarGanhoLayout.createSequentialGroup()
                        .addComponent(labelCadastrarGanhoAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastroGanhoLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarGanhoLayout.createSequentialGroup()
                        .addComponent(buttonCadastroGanhoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastroGanhoAdicionar)))
                .addContainerGap())
        );
        panelCadastrarGanhoLayout.setVerticalGroup(
            panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarGanhoAviso)
                    .addComponent(buttonCadastroGanhoLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadastroGanhoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCadastroGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCadastroGanhoAdicionar)
                    .addComponent(buttonCadastroGanhoCancelar))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Cadastrar", panelCadastrarGanho);

        labelRemoverGanhoAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelRemoverGanhoAviso.setText("Insira os dados do ganho a ser removido:");

        panelRemoverGanhoDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelRemoverGanhoDesc.setText("Descrição:");

        fieldInputRemoverGanhoDesc.setToolTipText("A descrição do ganho a ser removido.");

        javax.swing.GroupLayout panelRemoverGanhoDadosLayout = new javax.swing.GroupLayout(panelRemoverGanhoDados);
        panelRemoverGanhoDados.setLayout(panelRemoverGanhoDadosLayout);
        panelRemoverGanhoDadosLayout.setHorizontalGroup(
            panelRemoverGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRemoverGanhoDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldInputRemoverGanhoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRemoverGanhoDadosLayout.setVerticalGroup(
            panelRemoverGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoDesc)
                    .addComponent(fieldInputRemoverGanhoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRemoverGanhoData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelRemoverGanhoDia.setText("Dia:");

        labelRemoverGanhoMes.setText("Mês:");

        labelRemoverGanhoAno.setText("Ano:");

        spinnerRemoverGanhoDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerRemoverGanhoDia.setToolTipText("O dia em que o ganho ocorreu.");

        spinnerRemoverGanhoMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerRemoverGanhoMes.setToolTipText("O mês em que o ganho ocorreu.");

        spinnerRemoverGanhoAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerRemoverGanhoAno.setToolTipText("O ano em que o ganho ocorreu.");

        javax.swing.GroupLayout panelRemoverGanhoDataLayout = new javax.swing.GroupLayout(panelRemoverGanhoData);
        panelRemoverGanhoData.setLayout(panelRemoverGanhoDataLayout);
        panelRemoverGanhoDataLayout.setHorizontalGroup(
            panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRemoverGanhoDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemoverGanhoMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemoverGanhoAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerRemoverGanhoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRemoverGanhoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRemoverGanhoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelRemoverGanhoDataLayout.setVerticalGroup(
            panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoDia)
                    .addComponent(spinnerRemoverGanhoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoMes)
                    .addComponent(spinnerRemoverGanhoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoAno)
                    .addComponent(spinnerRemoverGanhoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonRemoverGanhoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonRemoverGanhoLimpar.setText("Limpar");
        buttonRemoverGanhoLimpar.setToolTipText("Limpar os campos da tela.");
        buttonRemoverGanhoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverGanhoLimparActionPerformed(evt);
            }
        });

        buttonRemoverGanhoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_delete.png"))); // NOI18N
        buttonRemoverGanhoRemover.setText("Remover");
        buttonRemoverGanhoRemover.setToolTipText("Remover ganho armazenado.");

        buttonRemoverGanhoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonRemoverGanhoCancelar.setText("Cancelar");
        buttonRemoverGanhoCancelar.setToolTipText("Cancelar remoção de ganho.");
        buttonRemoverGanhoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverGanhoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneRemoverGanhoLayout = new javax.swing.GroupLayout(paneRemoverGanho);
        paneRemoverGanho.setLayout(paneRemoverGanhoLayout);
        paneRemoverGanhoLayout.setHorizontalGroup(
            paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                        .addComponent(labelRemoverGanhoAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(buttonRemoverGanhoLimpar))
                    .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                        .addComponent(panelRemoverGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRemoverGanhoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRemoverGanhoLayout.createSequentialGroup()
                        .addComponent(buttonRemoverGanhoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRemoverGanhoRemover)))
                .addContainerGap())
        );
        paneRemoverGanhoLayout.setVerticalGroup(
            paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoAviso)
                    .addComponent(buttonRemoverGanhoLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRemoverGanhoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRemoverGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRemoverGanhoRemover)
                    .addComponent(buttonRemoverGanhoCancelar))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Remover", paneRemoverGanho);

        labelCadastrarGanhoAviso1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCadastrarGanhoAviso1.setText("Insira os dados do ganho a ser buscado:");

        panelCadastroGanhoData1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelBuscarGanhoDataDia.setText("Dia:");

        spinnerBuscarGanhoDataDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerBuscarGanhoDataDia.setToolTipText("O dia em que o ganho ocorreu.");

        labelBuscarGanhoDataMes.setText("Mês:");

        labelBuscarGanhoDataAno.setText("Ano:");

        spinnerBuscarGanhoDataMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerBuscarGanhoDataMes.setToolTipText("O mês em que o ganho ocorreu.");

        spinnerBuscarGanhoDataAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerBuscarGanhoDataAno.setToolTipText("O ano em que o ganho ocorreu.");

        javax.swing.GroupLayout panelCadastroGanhoData1Layout = new javax.swing.GroupLayout(panelCadastroGanhoData1);
        panelCadastroGanhoData1.setLayout(panelCadastroGanhoData1Layout);
        panelCadastroGanhoData1Layout.setHorizontalGroup(
            panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoData1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBuscarGanhoDataDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBuscarGanhoDataMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBuscarGanhoDataAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerBuscarGanhoDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerBuscarGanhoDataDia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerBuscarGanhoDataMes, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        panelCadastroGanhoData1Layout.setVerticalGroup(
            panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoData1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarGanhoDataDia)
                    .addComponent(spinnerBuscarGanhoDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarGanhoDataMes)
                    .addComponent(spinnerBuscarGanhoDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarGanhoDataAno)
                    .addComponent(spinnerBuscarGanhoDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCadastroGanhoDados1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelBuscarGanhoDesc.setText("Descrição:");

        labelBuscarGanhoValor.setText("Valor:");

        fieldInputBuscarGanhoDesc.setToolTipText("A descrição do ganho a ser buscado.");

        fieldOutputBuscarGanhoValor.setEditable(false);

        javax.swing.GroupLayout panelCadastroGanhoDados1Layout = new javax.swing.GroupLayout(panelCadastroGanhoDados1);
        panelCadastroGanhoDados1.setLayout(panelCadastroGanhoDados1Layout);
        panelCadastroGanhoDados1Layout.setHorizontalGroup(
            panelCadastroGanhoDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBuscarGanhoValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBuscarGanhoDesc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldInputBuscarGanhoDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(fieldOutputBuscarGanhoValor))
                .addContainerGap())
        );
        panelCadastroGanhoDados1Layout.setVerticalGroup(
            panelCadastroGanhoDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDados1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarGanhoDesc)
                    .addComponent(fieldInputBuscarGanhoDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBuscarGanhoValor)
                    .addComponent(fieldOutputBuscarGanhoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonBuscarGanhoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonBuscarGanhoLimpar.setText("Limpar");
        buttonBuscarGanhoLimpar.setToolTipText("Limpar os campos da tela.");
        buttonBuscarGanhoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarGanhoLimparActionPerformed(evt);
            }
        });

        buttonBuscarGanhoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonBuscarGanhoCancelar.setText("Cancelar");
        buttonBuscarGanhoCancelar.setToolTipText("Cancelar a busca.");
        buttonBuscarGanhoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarGanhoCancelarActionPerformed(evt);
            }
        });

        buttonBuscarGanhoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_buscar.png"))); // NOI18N
        buttonBuscarGanhoBuscar.setText("Buscar");
        buttonBuscarGanhoBuscar.setToolTipText("Buscar ganho no banco de dados.");
        buttonBuscarGanhoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarGanhoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarGanhoLayout = new javax.swing.GroupLayout(panelBuscarGanho);
        panelBuscarGanho.setLayout(panelBuscarGanhoLayout);
        panelBuscarGanhoLayout.setHorizontalGroup(
            panelBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarGanhoLayout.createSequentialGroup()
                        .addComponent(panelCadastroGanhoDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCadastroGanhoData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarGanhoLayout.createSequentialGroup()
                        .addComponent(labelCadastrarGanhoAviso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBuscarGanhoLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarGanhoLayout.createSequentialGroup()
                        .addComponent(buttonBuscarGanhoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBuscarGanhoBuscar)))
                .addContainerGap())
        );
        panelBuscarGanhoLayout.setVerticalGroup(
            panelBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarGanhoAviso1)
                    .addComponent(buttonBuscarGanhoLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadastroGanhoData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCadastroGanhoDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonBuscarGanhoBuscar)
                    .addComponent(buttonBuscarGanhoCancelar))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Buscar", panelBuscarGanho);

        javax.swing.GroupLayout panelListarGanhoLayout = new javax.swing.GroupLayout(panelListarGanho);
        panelListarGanho.setLayout(panelListarGanhoLayout);
        panelListarGanhoLayout.setHorizontalGroup(
            panelListarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        panelListarGanhoLayout.setVerticalGroup(
            panelListarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Listar", panelListarGanho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastroGanhoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroGanhoCancelarActionPerformed
       // Descartando a janela atual
        this.dispose();
    }//GEN-LAST:event_buttonCadastroGanhoCancelarActionPerformed

    private void buttonRemoverGanhoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverGanhoCancelarActionPerformed
        // Descartando a janela atual
        this.dispose();
    }//GEN-LAST:event_buttonRemoverGanhoCancelarActionPerformed

    private void buttonBuscarGanhoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarGanhoCancelarActionPerformed
        // Descartando a janela atual
        this.dispose();
    }//GEN-LAST:event_buttonBuscarGanhoCancelarActionPerformed

    private void buttonCadastroGanhoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroGanhoAdicionarActionPerformed
        //Fazendo leitura dos campos
        String desc = this.fieldInputCadastrarGanhoDesc.getText();
        float valor = Float.parseFloat(this.fieldInputCadastrarGanhoValor.getText());
        int dia, mes, ano;
        dia = (int) this.spinnerCadastroGanhoDataDia.getValue();
        mes = (int) this.spinnerCadastroGanhoDataMes.getValue();
        ano = (int) this.spinnerCadastroGanhoDataAno.getValue();
        //Criando novo objeto ganho
        Ganho g = new Ganho(valor, desc, dia, mes, ano);
        //Tentando inserir o ganho na database
        if(core.inserirGanho(g)){
            //...ganho cadastrado com êxito.
            //@todo Melhorar mensagens dos dialogs.
            JOptionPane.showMessageDialog(null, "Os dados foram cadastrados com êxito.");
        }else{
            //...houve um erro ao cadastrar o ganho.
            //O erro será exibido pelo próprio método de inserir
        }
    }//GEN-LAST:event_buttonCadastroGanhoAdicionarActionPerformed

    private void limparFields(){
        this.fieldInputBuscarGanhoDesc.setText("");
        this.fieldOutputBuscarGanhoValor.setText("");
        this.fieldInputCadastrarGanhoDesc.setText("");
        this.fieldInputCadastrarGanhoValor.setText("");
        this.fieldInputRemoverGanhoDesc.setText("");
        this.spinnerCadastroGanhoDataAno.setValue((int) 2000);
        this.spinnerCadastroGanhoDataMes.setValue((int) 1);
        this.spinnerCadastroGanhoDataDia.setValue((int) 1);
        this.spinnerBuscarGanhoDataAno.setValue((int) 2000);
        this.spinnerBuscarGanhoDataMes.setValue((int) 1);
        this.spinnerBuscarGanhoDataDia.setValue((int) 1);
        this.spinnerRemoverGanhoAno.setValue((int) 2000);
        this.spinnerRemoverGanhoMes.setValue((int) 1);
        this.spinnerRemoverGanhoDia.setValue((int) 1);
        
    }
    private void buttonCadastroGanhoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroGanhoLimparActionPerformed
        //@todo Implementar método para limpar TODOS os campos da JanelaGanhos
        this.limparFields();
    }//GEN-LAST:event_buttonCadastroGanhoLimparActionPerformed

    private void buttonRemoverGanhoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverGanhoLimparActionPerformed
        //@todo Implementar método para limpar TODOS os campos da JanelaGanhos
    }//GEN-LAST:event_buttonRemoverGanhoLimparActionPerformed

    private void buttonBuscarGanhoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarGanhoLimparActionPerformed
        //@todo Implementar método para limpar TODOS os campos da JanelaGanhos
    }//GEN-LAST:event_buttonBuscarGanhoLimparActionPerformed

    private void buttonBuscarGanhoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarGanhoBuscarActionPerformed
        //Fazendo leitura das variaveis
        String desc = this.fieldInputBuscarGanhoDesc.getText();
        int dia, mes, ano;
        dia = (int) this.spinnerBuscarGanhoDataDia.getValue();
        mes = (int) this.spinnerBuscarGanhoDataMes.getValue();
        ano = (int) this.spinnerBuscarGanhoDataAno.getValue();
        //Realizando busca
        Ganho g = this.core.buscarGanho(dia, mes, ano, desc);
        this.fieldOutputBuscarGanhoValor.setText(String.valueOf(g.getValor()));
    }//GEN-LAST:event_buttonBuscarGanhoBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaGanhos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarGanhoBuscar;
    private javax.swing.JButton buttonBuscarGanhoCancelar;
    private javax.swing.JButton buttonBuscarGanhoLimpar;
    private javax.swing.JButton buttonCadastroGanhoAdicionar;
    private javax.swing.JButton buttonCadastroGanhoCancelar;
    private javax.swing.JButton buttonCadastroGanhoLimpar;
    private javax.swing.JButton buttonRemoverGanhoCancelar;
    private javax.swing.JButton buttonRemoverGanhoLimpar;
    private javax.swing.JButton buttonRemoverGanhoRemover;
    private javax.swing.JTextField fieldInputBuscarGanhoDesc;
    private javax.swing.JTextField fieldInputCadastrarGanhoDesc;
    private javax.swing.JTextField fieldInputCadastrarGanhoValor;
    private javax.swing.JTextField fieldInputRemoverGanhoDesc;
    private javax.swing.JTextField fieldOutputBuscarGanhoValor;
    private javax.swing.JLabel labelBuscarGanhoDataAno;
    private javax.swing.JLabel labelBuscarGanhoDataDia;
    private javax.swing.JLabel labelBuscarGanhoDataMes;
    private javax.swing.JLabel labelBuscarGanhoDesc;
    private javax.swing.JLabel labelBuscarGanhoValor;
    private javax.swing.JLabel labelCadastrarGanhoAviso;
    private javax.swing.JLabel labelCadastrarGanhoAviso1;
    private javax.swing.JLabel labelCadastrarGanhoDesc;
    private javax.swing.JLabel labelCadastrarGanhoValor;
    private javax.swing.JLabel labelCadastroGanhoDataAno;
    private javax.swing.JLabel labelCadastroGanhoDataDia;
    private javax.swing.JLabel labelCadastroGanhoDataMes;
    private javax.swing.JLabel labelRemoverGanhoAno;
    private javax.swing.JLabel labelRemoverGanhoAviso;
    private javax.swing.JLabel labelRemoverGanhoDesc;
    private javax.swing.JLabel labelRemoverGanhoDia;
    private javax.swing.JLabel labelRemoverGanhoMes;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel paneRemoverGanho;
    private javax.swing.JPanel panelBuscarGanho;
    private javax.swing.JPanel panelCadastrarGanho;
    private javax.swing.JPanel panelCadastroGanhoDados;
    private javax.swing.JPanel panelCadastroGanhoDados1;
    private javax.swing.JPanel panelCadastroGanhoData;
    private javax.swing.JPanel panelCadastroGanhoData1;
    private javax.swing.JPanel panelListarGanho;
    private javax.swing.JPanel panelRemoverGanhoDados;
    private javax.swing.JPanel panelRemoverGanhoData;
    private javax.swing.JSpinner spinnerBuscarGanhoDataAno;
    private javax.swing.JSpinner spinnerBuscarGanhoDataDia;
    private javax.swing.JSpinner spinnerBuscarGanhoDataMes;
    private javax.swing.JSpinner spinnerCadastroGanhoDataAno;
    private javax.swing.JSpinner spinnerCadastroGanhoDataDia;
    private javax.swing.JSpinner spinnerCadastroGanhoDataMes;
    private javax.swing.JSpinner spinnerRemoverGanhoAno;
    private javax.swing.JSpinner spinnerRemoverGanhoDia;
    private javax.swing.JSpinner spinnerRemoverGanhoMes;
    // End of variables declaration//GEN-END:variables
}
