/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Thiago Matos
 */
public class JanelaGanhos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaGanhos
     */
    public JanelaGanhos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        panelCadastrarGanho = new javax.swing.JPanel();
        labelCadastrarGanhoAviso = new javax.swing.JLabel();
        panelCadastroGanhoData = new javax.swing.JPanel();
        labelCadastroGanhoDataDia = new javax.swing.JLabel();
        spinnerCadastroGanhoDataDia = new javax.swing.JSpinner();
        labelCadastroGanhoDataMes = new javax.swing.JLabel();
        labelCadastroGanhoDataAno = new javax.swing.JLabel();
        spinnerCadastroGanhoDataMes = new javax.swing.JSpinner();
        spinnerCadastroGanhoDataAno = new javax.swing.JSpinner();
        panelCadastroGanhoDados = new javax.swing.JPanel();
        labelCadastrarGanhoDesc = new javax.swing.JLabel();
        labelCadastrarGanhoValor = new javax.swing.JLabel();
        fieldInputCadastrarGanhoDesc = new javax.swing.JTextField();
        fieldInputCadastrarGanhoValor = new javax.swing.JFormattedTextField();
        buttonCadastroGanhoLimpar = new javax.swing.JButton();
        buttonCadastroGanhoCancelar = new javax.swing.JButton();
        buttonCadastroGanhoAdicionar = new javax.swing.JButton();
        paneRemoverGanho = new javax.swing.JPanel();
        labelRemoverGanhoAviso = new javax.swing.JLabel();
        panelRemoverGanhoDados = new javax.swing.JPanel();
        labelRemoverGanhoDesc = new javax.swing.JLabel();
        fieldInputRemoverGanhoDesc = new javax.swing.JTextField();
        panelRemoverGanhoData = new javax.swing.JPanel();
        labelRemoverGanhoDia = new javax.swing.JLabel();
        labelRemoverGanhoMes = new javax.swing.JLabel();
        labelRemoverGanhoAno = new javax.swing.JLabel();
        spinnerRemoverGanhoDia = new javax.swing.JSpinner();
        spinnerRemoverGanhoMes = new javax.swing.JSpinner();
        spinnerRemoverGanhoAno = new javax.swing.JSpinner();
        buttonRemoverGanhoLimpar = new javax.swing.JButton();
        buttonRemoverGanhoRemover = new javax.swing.JButton();
        buttonRemoverGanhoCancelar = new javax.swing.JButton();
        paneBuscarGanho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[SGF - 2014] Ganhos");
        setLocationByPlatform(true);
        setResizable(false);

        labelCadastrarGanhoAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCadastrarGanhoAviso.setText("Insira os dados do ganho a ser cadastrado:");

        panelCadastroGanhoData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelCadastroGanhoDataDia.setText("Dia:");

        spinnerCadastroGanhoDataDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerCadastroGanhoDataDia.setToolTipText("Insira o dia componente da data.");

        labelCadastroGanhoDataMes.setText("Mês:");

        labelCadastroGanhoDataAno.setText("Ano:");

        spinnerCadastroGanhoDataMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerCadastroGanhoDataMes.setToolTipText("Insira o mês componente da data.");

        spinnerCadastroGanhoDataAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerCadastroGanhoDataAno.setToolTipText("Insira o ano componente da data.");

        javax.swing.GroupLayout panelCadastroGanhoDataLayout = new javax.swing.GroupLayout(panelCadastroGanhoData);
        panelCadastroGanhoData.setLayout(panelCadastroGanhoDataLayout);
        panelCadastroGanhoDataLayout.setHorizontalGroup(
            panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastroGanhoDataDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastroGanhoDataMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastroGanhoDataAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerCadastroGanhoDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerCadastroGanhoDataDia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerCadastroGanhoDataMes, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        panelCadastroGanhoDataLayout.setVerticalGroup(
            panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroGanhoDataDia)
                    .addComponent(spinnerCadastroGanhoDataDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroGanhoDataMes)
                    .addComponent(spinnerCadastroGanhoDataMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroGanhoDataAno)
                    .addComponent(spinnerCadastroGanhoDataAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCadastroGanhoDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelCadastrarGanhoDesc.setText("Descrição:");

        labelCadastrarGanhoValor.setText("Valor:");

        fieldInputCadastrarGanhoDesc.setToolTipText("Insira uma descrição dos dados.");

        fieldInputCadastrarGanhoValor.setToolTipText("Insira o valor dos dados.");
        fieldInputCadastrarGanhoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldInputCadastrarGanhoValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastroGanhoDadosLayout = new javax.swing.GroupLayout(panelCadastroGanhoDados);
        panelCadastroGanhoDados.setLayout(panelCadastroGanhoDadosLayout);
        panelCadastroGanhoDadosLayout.setHorizontalGroup(
            panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastrarGanhoValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCadastrarGanhoDesc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldInputCadastrarGanhoDesc)
                    .addGroup(panelCadastroGanhoDadosLayout.createSequentialGroup()
                        .addComponent(fieldInputCadastrarGanhoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCadastroGanhoDadosLayout.setVerticalGroup(
            panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarGanhoDesc)
                    .addComponent(fieldInputCadastrarGanhoDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldInputCadastrarGanhoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCadastrarGanhoValor))
                .addContainerGap())
        );

        buttonCadastroGanhoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonCadastroGanhoLimpar.setText("Limpar");
        buttonCadastroGanhoLimpar.setToolTipText("Limpar os campos da tela.");

        buttonCadastroGanhoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonCadastroGanhoCancelar.setText("Cancelar");
        buttonCadastroGanhoCancelar.setToolTipText("Cancelar o cadastro.");

        buttonCadastroGanhoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_adicionar.png"))); // NOI18N
        buttonCadastroGanhoAdicionar.setText("Adicionar");
        buttonCadastroGanhoAdicionar.setToolTipText("Cadastrar o ganho no banco de dados.");

        javax.swing.GroupLayout panelCadastrarGanhoLayout = new javax.swing.GroupLayout(panelCadastrarGanho);
        panelCadastrarGanho.setLayout(panelCadastrarGanhoLayout);
        panelCadastrarGanhoLayout.setHorizontalGroup(
            panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarGanhoLayout.createSequentialGroup()
                        .addComponent(panelCadastroGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCadastroGanhoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarGanhoLayout.createSequentialGroup()
                        .addComponent(labelCadastrarGanhoAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastroGanhoLimpar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastrarGanhoLayout.createSequentialGroup()
                        .addComponent(buttonCadastroGanhoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCadastroGanhoAdicionar)))
                .addContainerGap())
        );
        panelCadastrarGanhoLayout.setVerticalGroup(
            panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastrarGanhoAviso)
                    .addComponent(buttonCadastroGanhoLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadastroGanhoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCadastroGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCadastroGanhoAdicionar)
                    .addComponent(buttonCadastroGanhoCancelar))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Cadastrar", panelCadastrarGanho);

        labelRemoverGanhoAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelRemoverGanhoAviso.setText("Insira os dados do ganho a ser removido:");

        panelRemoverGanhoDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        labelRemoverGanhoDesc.setText("Descrição:");

        fieldInputRemoverGanhoDesc.setToolTipText("Insira uma descrição dos dados.");

        javax.swing.GroupLayout panelRemoverGanhoDadosLayout = new javax.swing.GroupLayout(panelRemoverGanhoDados);
        panelRemoverGanhoDados.setLayout(panelRemoverGanhoDadosLayout);
        panelRemoverGanhoDadosLayout.setHorizontalGroup(
            panelRemoverGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRemoverGanhoDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldInputRemoverGanhoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRemoverGanhoDadosLayout.setVerticalGroup(
            panelRemoverGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverGanhoDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoDesc)
                    .addComponent(fieldInputRemoverGanhoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRemoverGanhoData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data"));

        labelRemoverGanhoDia.setText("Dia:");

        labelRemoverGanhoMes.setText("Mês:");

        labelRemoverGanhoAno.setText("Ano:");

        spinnerRemoverGanhoDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        spinnerRemoverGanhoDia.setToolTipText("Insira o dia componente da data.");

        spinnerRemoverGanhoMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        spinnerRemoverGanhoMes.setToolTipText("Insira o mês componente da data.");

        spinnerRemoverGanhoAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        spinnerRemoverGanhoAno.setToolTipText("Insira o ano componente da data.");

        javax.swing.GroupLayout panelRemoverGanhoDataLayout = new javax.swing.GroupLayout(panelRemoverGanhoData);
        panelRemoverGanhoData.setLayout(panelRemoverGanhoDataLayout);
        panelRemoverGanhoDataLayout.setHorizontalGroup(
            panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRemoverGanhoDia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemoverGanhoMes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRemoverGanhoAno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerRemoverGanhoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRemoverGanhoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRemoverGanhoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelRemoverGanhoDataLayout.setVerticalGroup(
            panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRemoverGanhoDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoDia)
                    .addComponent(spinnerRemoverGanhoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoMes)
                    .addComponent(spinnerRemoverGanhoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRemoverGanhoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoAno)
                    .addComponent(spinnerRemoverGanhoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonRemoverGanhoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_limpar.png"))); // NOI18N
        buttonRemoverGanhoLimpar.setText("Limpar");
        buttonRemoverGanhoLimpar.setToolTipText("Limpar os campos da tela.");

        buttonRemoverGanhoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_delete.png"))); // NOI18N
        buttonRemoverGanhoRemover.setText("Remover");
        buttonRemoverGanhoRemover.setToolTipText("Remover ganho armazenado.");

        buttonRemoverGanhoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        buttonRemoverGanhoCancelar.setText("Cancelar");
        buttonRemoverGanhoCancelar.setToolTipText("Cancelar remoção de ganho.");

        javax.swing.GroupLayout paneRemoverGanhoLayout = new javax.swing.GroupLayout(paneRemoverGanho);
        paneRemoverGanho.setLayout(paneRemoverGanhoLayout);
        paneRemoverGanhoLayout.setHorizontalGroup(
            paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                        .addComponent(labelRemoverGanhoAviso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(buttonRemoverGanhoLimpar))
                    .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                        .addComponent(panelRemoverGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRemoverGanhoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRemoverGanhoLayout.createSequentialGroup()
                        .addComponent(buttonRemoverGanhoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRemoverGanhoRemover)))
                .addContainerGap())
        );
        paneRemoverGanhoLayout.setVerticalGroup(
            paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoverGanhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverGanhoAviso)
                    .addComponent(buttonRemoverGanhoLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRemoverGanhoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRemoverGanhoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRemoverGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRemoverGanhoRemover)
                    .addComponent(buttonRemoverGanhoCancelar))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Remover", paneRemoverGanho);

        javax.swing.GroupLayout paneBuscarGanhoLayout = new javax.swing.GroupLayout(paneBuscarGanho);
        paneBuscarGanho.setLayout(paneBuscarGanhoLayout);
        paneBuscarGanhoLayout.setHorizontalGroup(
            paneBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
        paneBuscarGanhoLayout.setVerticalGroup(
            paneBuscarGanhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Buscar", paneBuscarGanho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldInputCadastrarGanhoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldInputCadastrarGanhoValorActionPerformed
        
    }//GEN-LAST:event_fieldInputCadastrarGanhoValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaGanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaGanhos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastroGanhoAdicionar;
    private javax.swing.JButton buttonCadastroGanhoCancelar;
    private javax.swing.JButton buttonCadastroGanhoLimpar;
    private javax.swing.JButton buttonRemoverGanhoCancelar;
    private javax.swing.JButton buttonRemoverGanhoLimpar;
    private javax.swing.JButton buttonRemoverGanhoRemover;
    private javax.swing.JTextField fieldInputCadastrarGanhoDesc;
    private javax.swing.JFormattedTextField fieldInputCadastrarGanhoValor;
    private javax.swing.JTextField fieldInputRemoverGanhoDesc;
    private javax.swing.JLabel labelCadastrarGanhoAviso;
    private javax.swing.JLabel labelCadastrarGanhoDesc;
    private javax.swing.JLabel labelCadastrarGanhoValor;
    private javax.swing.JLabel labelCadastroGanhoDataAno;
    private javax.swing.JLabel labelCadastroGanhoDataDia;
    private javax.swing.JLabel labelCadastroGanhoDataMes;
    private javax.swing.JLabel labelRemoverGanhoAno;
    private javax.swing.JLabel labelRemoverGanhoAviso;
    private javax.swing.JLabel labelRemoverGanhoDesc;
    private javax.swing.JLabel labelRemoverGanhoDia;
    private javax.swing.JLabel labelRemoverGanhoMes;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel paneBuscarGanho;
    private javax.swing.JPanel paneRemoverGanho;
    private javax.swing.JPanel panelCadastrarGanho;
    private javax.swing.JPanel panelCadastroGanhoDados;
    private javax.swing.JPanel panelCadastroGanhoData;
    private javax.swing.JPanel panelRemoverGanhoDados;
    private javax.swing.JPanel panelRemoverGanhoData;
    private javax.swing.JSpinner spinnerCadastroGanhoDataAno;
    private javax.swing.JSpinner spinnerCadastroGanhoDataDia;
    private javax.swing.JSpinner spinnerCadastroGanhoDataMes;
    private javax.swing.JSpinner spinnerRemoverGanhoAno;
    private javax.swing.JSpinner spinnerRemoverGanhoDia;
    private javax.swing.JSpinner spinnerRemoverGanhoMes;
    // End of variables declaration//GEN-END:variables
}
