/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author AlvesRC
 */
public class WizardGraficoUm extends javax.swing.JFrame {

    /**
     * Creates new form WizardGraficoUm
     */
    public WizardGraficoUm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIntro = new javax.swing.JLabel();
        labelAviso = new javax.swing.JLabel();
        panelDados = new javax.swing.JPanel();
        checkBoxGanhos = new javax.swing.JCheckBox();
        checkBoxDespesas = new javax.swing.JCheckBox();
        panelOpcional = new javax.swing.JPanel();
        checkBoxEspecifica = new javax.swing.JCheckBox();
        labelDesc = new javax.swing.JLabel();
        fieldInputDesc = new javax.swing.JTextField();
        butttonCancelar = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[SGF - 2014] Gerar Gráfico (1 / 2)");

        labelIntro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelIntro.setText("Seja bem vindo ao Wizard para a criação do gráfico.");

        labelAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAviso.setText("Escolha abaixo os dados a serem exibidos:");

        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        checkBoxGanhos.setText("Ganhos");
        checkBoxGanhos.setToolTipText("Selecione para exibir Ganhos no gráfico.");
        checkBoxGanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxGanhosActionPerformed(evt);
            }
        });

        checkBoxDespesas.setText("Despesas");
        checkBoxDespesas.setToolTipText("Selecione para exibir Despesas no gráfico.");

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxDespesas)
                    .addComponent(checkBoxGanhos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxGanhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxDespesas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOpcional.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opcional"));

        checkBoxEspecifica.setText("Específica");
        checkBoxEspecifica.setToolTipText("Selecione caso deseje exibir no gráfico apenas despesas específicas.");
        checkBoxEspecifica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxEspecificaStateChanged(evt);
            }
        });

        labelDesc.setText("Descrição:");

        fieldInputDesc.setEditable(false);
        fieldInputDesc.setToolTipText("Descrição específica a ser exibida.");

        javax.swing.GroupLayout panelOpcionalLayout = new javax.swing.GroupLayout(panelOpcional);
        panelOpcional.setLayout(panelOpcionalLayout);
        panelOpcionalLayout.setHorizontalGroup(
            panelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionalLayout.createSequentialGroup()
                        .addComponent(checkBoxEspecifica)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelOpcionalLayout.createSequentialGroup()
                        .addComponent(labelDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldInputDesc)))
                .addContainerGap())
        );
        panelOpcionalLayout.setVerticalGroup(
            panelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxEspecifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOpcionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesc)
                    .addComponent(fieldInputDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        butttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_cancelar.png"))); // NOI18N
        butttonCancelar.setText("Cancelar");
        butttonCancelar.setToolTipText("Cancelar a criação do gráfico.");

        buttonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/24px_next.png"))); // NOI18N
        buttonProximo.setText("Próximo");
        buttonProximo.setToolTipText("Ir para o próximo passo na criação do gráfico.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butttonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonProximo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIntro)
                            .addComponent(labelAviso))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelOpcional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIntro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOpcional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butttonCancelar)
                    .addComponent(buttonProximo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxGanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxGanhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxGanhosActionPerformed

    private void checkBoxEspecificaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxEspecificaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxEspecificaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardGraficoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardGraficoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardGraficoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardGraficoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WizardGraficoUm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProximo;
    private javax.swing.JButton butttonCancelar;
    private javax.swing.JCheckBox checkBoxDespesas;
    private javax.swing.JCheckBox checkBoxEspecifica;
    private javax.swing.JCheckBox checkBoxGanhos;
    private javax.swing.JTextField fieldInputDesc;
    private javax.swing.JLabel labelAviso;
    private javax.swing.JLabel labelDesc;
    private javax.swing.JLabel labelIntro;
    private javax.swing.JPanel panelDados;
    private javax.swing.JPanel panelOpcional;
    // End of variables declaration//GEN-END:variables
}
